# Generated by Django 5.2.4 on 2025-08-05 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='키(cm)')),
                ('weight', models.PositiveIntegerField(blank=True, null=True, verbose_name='몸무게(kg)')),
                ('age', models.PositiveIntegerField(blank=True, null=True, verbose_name='나이')),
                ('gender', models.CharField(blank=True, choices=[('M', '남'), ('F', '여')], max_length=1, null=True, verbose_name='성별')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
